on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Go mod download
        run: go mod download

      - name: Compile
        run: |
          CGO_ENABLED=0 go build -o /tmp/sd github.com/netdata/sd/cmd/sd
          /tmp/sd --help || true

      - name: Enforce formatted code
        run: "! go fmt ./... 2>&1 | read"

      - name: Go vet
        run: go vet ./...

      - name: Go test
        run: go test ./... -race -count=1

      - name: Golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
